# Generated by Django 3.2 on 2024-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default=None, null=True, upload_to='api/media/')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('going', 'Going'), ('done', 'Done')], default='to_do', max_length=10)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
